### ISSUE TITLE
Typo in github repository description

### ISSUE THREAD

**Issue by stepanzubkov** [nasa/fprime-tools#135]
| | |
|:---|:---|
|**_F´ Version_**| devel |
|**_Affected Component_**|  repository |
---
## Problem Description

The github repo descriptions is: *F´ python tooling and helpers. Formally Fw/Pyhon*. There is typo in word Pyhon. It looks like it should be Python.

**Comment by thomas-bc** [comment]
Also, should it be _Formerly_ and not Formally?
We may want to revisit the description of this repo to modernize it.

**Comment by thomas-bc** [comment]
Fixed.
