### ISSUE TITLE
add license option when generating project scaffold with `fprime-util new --project`

### ISSUE THREAD

**Issue by capsulecorplab** [nasa/fprime-tools#155]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Option to add an [OSI](https://opensource.org/about) approved license when generating project scaffold with `fprime-util new --project` - perhaps with default to Apache 2.0 to match core fprime codebase.

## Rationale

As to allow for ease of integration and contributions as an fprime community project

**Comment by LeStarch** [comment]
Moved to: https://github.com/nasa/fprime/issues/2225
