### ISSUE TITLE
include `.gitignore` as part of project scaffold with `fprime-util new --project`

### ISSUE THREAD

**Issue by capsulecorplab** [nasa/fprime-tools#156]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

New projects generated with `fprime-util new --project` should include a `.gitignore`

## Rationale

As to ensure artifacts, s.a., the build cache generated from `fprime-util generate`, don't accidentally get committed into git

**Comment by thomas-bc** [comment]
@capsulecorplab This is yet another thing that falls into the "coming in for next release" category haha. Here's what we have in `devel`: [.gitignore](https://github.com/fprime-community/fprime-tools/blob/devel/src/fprime/cookiecutter_templates/cookiecutter-fprime-project/%7B%7Bcookiecutter.project_name%7D%7D/.gitignore). Are there any other files you'd thing we should add in there?

**Comment by capsulecorplab** [comment]
> @capsulecorplab This is yet another thing that falls into the "coming in for next release" category haha. Here's what we have in `devel`: [.gitignore](https://github.com/fprime-community/fprime-tools/blob/devel/src/fprime/cookiecutter_templates/cookiecutter-fprime-project/%7B%7Bcookiecutter.project_name%7D%7D/.gitignore). Are there any other files you'd thing we should add in there?

Excellent! A license is the other thing that came to mind, which I already opened an issue for #155

**Comment by thomas-bc** [comment]
Will look into it! Thanks. Closing this issue.
