### ISSUE TITLE
invalid F prime deployment

### ISSUE THREAD

**Issue by Daifaizonaldridge** [nasa/fprime-tools#157]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**| Camera |
---
## Problem Description
I'm trying to create the implementation files for my camera component, and I keep getting an error.

A description of the problem with sufficient detail to understand the issue.
the command I used is "fprime-util impl" and I was in the camera component pathway when using the command. the error statement say's "[ERROR] /home/djaldridge/fprime/CaNOP_FSW/build-fprime-automatic-native is an invalid F prime deployment. Does not define any of the cache fields: FPRIME_PROJECT_ROOT,FPRIME_LIBRARY_LOCATIONS,FPRIME_FRAMEWORK_PATH"

Here's some images of the Linux terminal, the cmake files for the camera, and cmake files for the project:
![Screenshot 2023-07-28 091749](https://github.com/fprime-community/fprime-tools/assets/123976724/87be8ab0-e71e-4791-99e5-fdeb67d687e5)

![Screenshot 2023-07-28 091916](https://github.com/fprime-community/fprime-tools/assets/123976724/59483c6f-59a8-40d8-9413-3c23c01df211)

Continued cmake files for camera:
![Screenshot 2023-07-28 091933](https://github.com/fprime-community/fprime-tools/assets/123976724/51d1a927-9334-46ac-a3af-c9a8d598045a)

cmake files for project:
![Screenshot 2023-07-28 092201](https://github.com/fprime-community/fprime-tools/assets/123976724/60301247-4b5f-41f5-8dd2-a0e2e457e7d0)

## How to Reproduce

1. clone GitHub project.
2. went into component pathway.
3. use command "fprime-util impl".

## Expected Behavior
the component creates the implentation files.

A description of the expected behavior.
since I used the command "fprime-util impl", the camera component creates the implementation files.

**Comment by Daifaizonaldridge** [comment]
correction, I'm trying to generate basic implementation*

**Comment by thomas-bc** [comment]
Is there any chance you could share your repository? Also, make sure to run 'fprime-util generate' prior to running the impl command.

**Comment by Daifaizonaldridge** [comment]
good news, I was able to fix the error, this is going to sound weird but I I'm going to end this issue for now but thank you for trying to help me.
