### ISSUE TITLE
Sub-repo cloning script

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime-tools#24]
| | |
|:---|:---|
|**_F´ Version_**| n/a |
|**_Affected Component_**| n/a |
---
## Feature Description

It is more frequent that new projects are using F Prime as a sub-repo. It would be convenient to have a cloner script that sets up the sub-repos and local configs for the user. Here are the suggested features:

* Create an F Prime sub-repo with the correct release, tag, or commit
* Create a local `config` directory with a copy of what is in the F Prime repo.
* Copy `Ref` deployment to act as placeholder
* Create correct `cmake` files in new `Ref`.
* Check out F Prime sub-repo
* Build new `Ref` deployment (maybe?)

## Rationale

Make creating a sub-repo based repository easier and less error-prone.

**Comment by Joshua-Anderson** [comment]
It might be worth considering using cookiecutter templates like we do with `fprime-util new`.

**Comment by LeStarch** [comment]
@SterlingPeet is working on an `fprime-util new` for topologies/deployments.  I think that will meet this need.

**Comment by thomas-bc** [comment]
This will be addressed by the upcoming `fprime-util new --project` command

**Comment by thomas-bc** [comment]
`fprime-util new` is now (with `devel`, will be released soon) able to generate a project, which sets up everything needed for setting up a new F' project with the modern project structure, including cloning fprime as a subrepo.
