### ISSUE TITLE
FPP Visualization Automation

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime-tools#33]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Automate the fop-visualizations. https://github.com/nasa/fprime/pull/1167

**Comment by ThibFrgsGmz** [comment]
You mean integrate [FPL](https://github.com/fprime-community/fprime-layout) and [FPV](https://github.com/fprime-community/fprime-visual) ? That would be awesome indeed.

**Comment by LeStarch** [comment]
Yes, we want to directly integrate the large FPP suite of tools into `fprime-util`!  That way it is all fairly straight-forward to run.

**Comment by ThibFrgsGmz** [comment]
What would be the associated command?
Something like `fprime-util layout` and `fprime-util visual` ?
Or just a `fprime-util visual` command that takes care of running `fpl` and `fpv` ?

Just run it in a directory containing a deployment, and no path argument?

**Comment by thomas-bc** [comment]
Now tracked in https://github.com/nasa/fprime/issues/2059

Under development in https://github.com/thomas-bc/fprime-tools/tree/feat/fpp-visualize
We are also using a Flask'ed version of `fprime-visual`, planned to be released soon. See https://github.com/thomas-bc/fprime-visual/tree/refactor/flask

fprime-util visualize takes care of everything :) The workflow is 
- `cd Ref/Top`
- `fprime-util visualize`
- ???
- profit

**Comment by thomas-bc** [comment]
Released as of v3.3.0, `fprime-util visualize`
