### ISSUE TITLE
Add fpp to `fprime-util new`

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime-tools#37]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Currently `fprime-util new` generates XML.  We should augment it to generate FPP or XML per a flag.  

e.g
```
fprime-util new  # FPP (default)
fprime-util new --xml # XML old setup
```

**Comment by LeStarch** [comment]
Additionally we need to bump the cookiecutter version due to security concerns. See: nasa/fprime#1534.

**Comment by LeStarch** [comment]
Also see: nasa/fprime/issues/1244

**Comment by thomas-bc** [comment]
Done in the above PR. Cookiecutter has also been bumped.
