### ISSUE TITLE
`fprime-util -p` Does Not Respect CWD

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime-tools#45]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

When running with `fprime-util -p` it searches for a build cache starting at that directory (e.g -p).  It does not look for a build cache from cwd.  Thus `-d` and `-p` are not inverses.

```
cd <component>
fprime-util build -d <path to deployment> # builds with deployment
```

```
cd <deployment>
fprime-util build -p <path to component> # Does not build with deployment
```

This should be the case because to build with the detected deployment of a component is:

```
cd <component>
fprime-util build #Detected deployment
```

**Comment by Joshua-Anderson** [comment]
I intentionally designed this behavior - though whether it's correct or not is rightly up for debate.

My assumption was that most components will live within the folder of their deployment... which is often but not necessarily true.

I also assumed that users would primarily be using the `-p` argument from outside of the deployment directory, I.E. at the root directory of your project, in which case using the CWD for the deployment directory would be wrong.

How often are users in the deployment directory and using the `-p` directory to build an out of deployment directory component? It seems to me like assuming the component is within the deployment is more likely to be correct than assuming the user's CWD is within the deployment.

I don't have strong opinions here, it's seems like determining the intended deployment directory is a problem that doesn't have a perfect solution.
