### ISSUE TITLE
fprime-util purge native does not purge native

### ISSUE THREAD

**Issue by kevin-f-ortega** [nasa/fprime-tools#47]
| | |
|:---|:---|
|**_F´ Version_**| 47afb72e1f2cb79c1ab475458b0ed3faca5d317c |
|**_Affected Component_**|  fprime-tools Version: 3.0.1 |
---
## Problem Description

I have my default_toolchain defined as vxworks. When I purge native, fprime-tools tries to remove my vxworks build cache instead of my native build cache.

## How to Reproduce

1. Define default_toolchain in settings.ini to a non-native toolchain
2. fprime-util generate native
3. fprime-util purge native

## Expected Behavior

I expect purge native to remove the build-fprime-automatic-native build cache instead of build-fprime-automatic-vxworks.

**Comment by LeStarch** [comment]
Fixed by #54
